KEYCODE_SLASH=$2f
KEYCODE_DOWN=$11
KEYCODE_UP=$91
KEYCODE_LEFT=$9d
KEYCODE_RIGHT=$1d
KEYCODE_F1=$85
KEYCODE_F2=$89
KEYCODE_F3=$86
KEYCODE_F4=$8a
KEYCODE_F5=$87
KEYCODE_F6=$8b
KEYCODE_F7=$88
KEYCODE_F8=$8c
KEYCODE_ABORT=$03 ;RUN/STOP
.define KEYNAME_ABORT "RUN/STOP"
.export KEYCODE_ABORT