KPR_ERROR_PORT_IN_USE                   = $80
KPR_ERROR_TIMEOUT_ON_RECEIVE            = $81
KPR_ERROR_TRANSMIT_FAILED               = $82
KPR_ERROR_TRANSMISSION_REJECTED_BY_PEER = $83
KPR_ERROR_INPUT_TOO_LARGE               = $84
KPR_ERROR_DEVICE_FAILURE                = $85
KPR_ERROR_ABORTED_BY_USER               = $86
KPR_ERROR_LISTENER_NOT_AVAILABLE        = $87
KPR_ERROR_CONNECTION_RESET_BY_PEER      = $89
KPR_ERROR_CONNECTION_CLOSED             = $8A
KPR_ERROR_MALFORMED_URL                 = $A0
KPR_ERROR_DNS_LOOKUP_FAILED             = $A1



; -- LICENSE FOR error.inc --
; The contents of this file are subject to the Mozilla Public License
; Version 1.1 (the "License"); you may not use this file except in
; compliance with the License. You may obtain a copy of the License at
; http://www.mozilla.org/MPL/
;
; Software distributed under the License is distributed on an "AS IS"
; basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
; License for the specific language governing rights and limitations
; under the License.
;
; The Original Code is ip65.
;
; The Initial Developer of the Original Code is Jonno Downes,
; jonno@jamtronix.com.
; Portions created by the Initial Developer are Copyright (C) 2009
; Jonno Downes. All Rights Reserved.
; -- LICENSE END --
